version: '2'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    container_name: kafdrop
    hostname: kafdrop
    ports:
      - "9010:9000"
    external_links:
      - broker1
      - broker2
      - broker3
    environment:
      KAFKA_BROKERCONNECT: broker1:9091,broker2:9092,broker3:9093
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    networks:
      default:
        ipv4_address: 172.69.0.19
networks:
  default:
    external:
      name: kafka_zoo
